version: "3.5"
services: 
  jenkins-master:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins-data:/var/jenkins_home
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '2'
          memory: '2048M'
      # placement:
      #   constraints: 
      #     - "node.labels.zone != 1"
      #   preferences:
      #     - spread: node.labels.zone
    ports:
      - "8080:8080"
      - "5000:5000"
    secrets:
      jenkins-password:
        file: "jenkinspw"
      jenkins-username:
        file: "jenkinsuse"
