version: "3.5"
services: 
  jenkins-master:
    image: jenkins/jenkins:lts
    volumes:
      uploads_tmp_efs:
        driver: local
        driver_opts:
        type: nfs
        o: addr=[YOUR_EFS_DNS],nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '2'
          memory: '2048M'
    networks:
      - jenkins-network
      - bridge
    ports:
      - "8080:8080"
      - "5000:5000"
    networks:
      bridge:
        external: true
        name: bridge
      jenkins-network:
        driver: overlay
        attachable: true
    volumes:
      uploads_tmp_efs:
    secrets:
      jenkins-password:
        file: "jenkinspw"
      jenkins-username:
        file: "jenkinsuse"
