version: "3.5"
services: 
  jenkins-master:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins-data:/var/jenkins_home
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '2'
          memory: '2048M'
    networks:
      - jenkins-network
      - bridge
    ports:
      - "8080:8080"
      - "5000:5000"
    networks:
      bridge:
        external: true
        name: bridge
      jenkins-network:
        driver: overlay
        attachable: true
    volumes:
      jenkins-data:
    secrets:
      jenkins-password:
        file: "jenkinspw"
      jenkins-username:
        file: "jenkinsuse"
